# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directories:
      - "/"
      - "/gsat-core"
      - "/gsat-main"
      - "/gsat-kaon2"
      - "/gsat-utils"
      - "/gsat-commons"
      - "/gsat-utils/tgd-viz"
      - "/gsat-utils/owl2dlgp"
      - "/gsat-materialization"
      - "/gsat-utils/gsat-owl-sanitiser"
    schedule:
      interval: "weekly"
